config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :houses
  resources :reservations
  resources :hosts
  resources :guests

  get '/login', to: "auth#login", as: "login"
  post '/login', to: "auth#verify_first_name"

  get '/logout', to: "auth#logout", as: "logout"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    before_action :set_house, only:[:show, :edit, :update, :destroy]

    def index
        @houses = House.all

        if params[:bedrooms]
            @house = House.where('bedrooms >= ?', "#{params[:bedrooms]}")
        elsif params[:bathrooms]
            @house = House.where('bathrooms >= ?', "#{params[:bathrooms]}")
        elsif params[:parking]
            @house = House.where('parking >= ?', "#{params[:parking]}")
        elsif params[:guest_limit]
            @house = House.where('guest_limit >= ?', "#{params[:guest_limit]}")
        elsif params[:pet_friendly]
            @house = House.where('pet_friendly LIKE ?', "#{params[:pet_friendly]}")
        elsif params[:house_type]
            @house = House.where('house_type LIKE ?', "#{params[:house_type]}")
        elsif params[:cost_per_day]
            @house = House.where('cost_per_day <= ?', "#{params[:cost_per_day]}")
        else
            @house = House.all
        end
    end

    def show
        @house = House.find(params[:id])
        session[:house] = @house.id
    end

    def new
        @house = House.new(params[:id])
    end
    
    def create
        @house = House.new(house_params)
        if @house.save
            redirect_to @house
        else
            flash[:message] = @house.errors.full_messages
            render :new
        end
    end

    def update
        if @house.update(house_params)
        redirect_to host_path(@house.host_id)
        else 
        flash[:message] = @house.errors.full_messages 
		render :new 
        end 
    end

    def destroy
        id = @house.host_id
        @house.destroy
        redirect_to host_path(id)    
    end

    private

    def house_params
        params.require(:house).permit(:address, :bedrooms, :bathrooms, :parking, :guest_limit, :pet_friendly, :house_type, :host_id, :cost_per_day, :img_url, :search)
    end

    def set_house
        @house = House.find(params[:id])
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/edit.html.erb
<h1>Edit House</h1>

<%= flash[:message] %> 
<%= form_for @house do |f| %>
    <%= f.label "Address: " %>
    <%= f.text_field :address %> <br><br>

    <%= f.label "Beds: " %>
    <%= f.text_field :bedrooms %><br><br>

    <%= f.label "Baths: " %>
    <%= f.text_field :bathrooms %><br><br>

    <%= f.label "Parking spots: " %>
    <%= f.text_field :parking %><br><br>

    <%= f.label "Room for: " %>
    <%= f.text_field :guest_limit %><br><br>
    
    <%= f.label "Pet friendly? " %>
    <%= f.text_field :pet_friendly %><br><br>   

    <%= f.label "House Type: " %>
    <%= f.text_field :house_type %><br><br>

    <%= f.label "Host ID: " %>
    <%= f.text_field :host_id %><br><br>

    <%= f.label "Cost Per Day: " %>
    <%= f.text_field :cost_per_day %><br><br>

    <%= f.label "Image URL: " %>
    <%= f.text_field :img_url %><br><br> 
    
<%= f.submit %>
<% end %>

app/views/houses/index.html.erb
<h1>House Index</h1>

<h4>Search By: </h4>
Minimum Bedrooms
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :bedrooms, params[:bedrooms] %>
      <%= submit_tag ("Search") %>
   <% end %>
Minimum Bathrooms
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :bathrooms, params[:bathrooms] %>
      <%= submit_tag ("Search") %>
   <% end %>
Minimum Number of Parking Spots
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :parking, params[:parking] %>
      <%= submit_tag ("Search") %>
   <% end %>
Minimum Guest Capacity
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :guest_limit, params[:guest_limit] %>
      <%= submit_tag ("Search") %>
   <% end %>
Pet Friendly<br>(true = 1 /false = 0)
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :pet_friendly, params[:pet_friendly] %>
      <%= submit_tag ("Search") %>
   <% end %>
House Type
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :house_type, params[:house_type] %>
      <%= submit_tag ("Search") %>
   <% end %>
Maximum Cost per Day
   <%= form_tag(houses_path, method: :get) do %>
      <%= text_field_tag :cost_per_day, params[:cost_per_day] %>
      <%= submit_tag ("Search") %>
   <% end %>
<br>

<h3> All Available Houses:</h3>

   <% @house.map do |house| %>
      <div class="card-deck">
         <div class="card">
            <img src="<%= house.img_url %>" class="card-img-top" alt="pic of house">
            <div class="card-body">
               <h5 class="card-title">Address: <%= house.address %></h5>
               <p class="card-text">Bedrooms: <%= house.bedrooms %></p>
               <p class="card-text">Bathrooms: <%= house.bathrooms %></p>
               <p class="card-text">Capacity: <%= house.guest_limit %></p>
               <p class="card-text">Cost Per Day: $<%= house.cost_per_day %></p>
               <a href="<%= house_path house.id %>" class="btn btn-primary">View Stay</a>
            </div>
         </div>
      </div>      
  <% end %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= flash[:message] %> 
<%= form_for @house do |f| %>
    <b><%= f.label "Address: " %></b>
    <%= f.text_field :address %> <br><br>

    <b><%= f.label "Beds: " %></b>
    <%= f.text_field :bedrooms %><br><br>

    <b><%= f.label "Baths: " %></b>
    <%= f.text_field :bathrooms %><br><br>

    <b><%= f.label "Parking spots: " %></b>
    <%= f.text_field :parking %><br><br>

    <b><%= f.label "Room for: " %></b>
    <%= f.text_field :guest_limit %><br><br>
    
    <b><%= f.label "Pet friendly? (true/false) " %></b>
    <%= f.text_field :pet_friendly %><br><br>   

    <b><%= f.label "House Type: " %></b>
    <%= f.text_field :house_type %><br><br>

    <b><%= f.label "Cost Per Day: " %></b>
    <%= f.text_field :cost_per_day %><br><br>
    
    <b><%= f.label "Image URL: " %></b>
    <%= f.text_field :img_url %><br><br> 
    
    <%= f.hidden_field :host_id, value: session[:host] %>

<%= f.submit %>
<% end %>

app/views/houses/show.html.erb
<h1>House Show</h1>

<div class="card mb-3">
         <img src="<%= @house.img_url %>" class="card-img-top" alt="...">
         <div class="card-body">
            <h5 class="card-title"><%= @house.address %></h5>
            <p class="card-text">Bedrooms: <%= @house.bedrooms %></p>
            <p class="card-text">Bathrooms: <%= @house.bathrooms %></p>
            <p class="card-text">Capacity: <%= @house.guest_limit %></p>
            <p class="card-text">Cost Per Day: $<%= @house.cost_per_day %></p>
            <p class="card-text">Parking Spots: <%= @house.parking %></p>
            <p class="card-text">Pet Friendly: <%= @house.pet_friendly %></p>
            <p class="card-text">House Type: <%= @house.house_type %></p>

            <% if !!session[:guest] %>
            <a href="<%= new_reservation_path %>" class="btn btn-primary">Make Reservation</a>
            <% elsif !!session[:host] %>
            <a href="<%= host_path(@house.host_id) %>" class="btn btn-primary">Host Index</a>
            <% end %>
            
         </div>
      </div>

      