config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :houses
  resources :reservations
  resources :hosts
  resources :guests

  get '/login', to: "auth#login", as: "login"
  post '/login', to: "auth#verify_first_name"

  get '/logout', to: "auth#logout", as: "logout"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :guest
    belongs_to :house 
    has_many :messages 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :set_reservation, only:[:show, :edit, :update, :destroy, :reservation_address]
    # before_action :set_house, only:[:new, :create]

    def new
        @reservation = Reservation.new
    end

    def create
        @reservation = Reservation.new(reservation_params)
        if @reservation.save
            session[:reservation] = @reservation.id
            redirect_to guest_path(session[:guest])
        else
            flash[:message] = @reservation.errors.full_messages
            render :new
        end
    end

    def update
            if @reservation.update(reservation_params)
            redirect_to @reservation
            else 
            flash[:message] = @reservation.errors.full_messages 
            render :new 
            end
    end

    def destroy
        id = @reservation.guest_id
        @reservation.destroy
        redirect_to guest_path(id)  
    end

    private 
    
    def reservation_params
       params.require(:reservation).permit(:number_of_guests, :reservation_start_date, :reservation_end_date, :guest_id, :house_id)
    end

    def set_reservation
        @reservation = Reservation.find(params[:id])
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= flash[:message] %> 
<%= form_for @reservation do |f| %>
    <%= f.label "Number of Guests: " %>
    <%= f.text_field :number_of_guests %> <br><br>

    <%= f.label "Start Date: " %>
    <%= f.text_field :reservation_start_date %><br><br>

    <%= f.label "End Date: " %>
    <%= f.text_field :reservation_end_date %><br><br>
<%= f.submit %>
<% end %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1><br>

<%= flash[:message] %> 
<%= form_for @reservation do |f| %>
    <%= f.label "Number of Guests: " %>
    <%= f.text_field :number_of_guests %> <br><br>

    <%= f.label "Start Date: " %>
    <%= f.text_field :reservation_start_date %><br><br>

    <%= f.label "End Date: " %>
    <%= f.text_field :reservation_end_date %><br><br>

    <%= f.hidden_field :guest_id, value: session[:guest] %>
    <%= f.hidden_field :house_id, value: session[:house] %>

<%= f.submit %>
<% end %>

app/views/reservations/show.html.erb
<h1>Reservation Show</h1>

<div class="card" style="width: 25rem;">
    <div class="card-body">
        <b>Reservation Number: <%= @reservation.id %></b><br>
        Number of Guests: <%= @reservation.number_of_guests %><br> 
        Starting Date: <%= @reservation.reservation_start_date %><br>    
        Ending Date: <%= @reservation.reservation_end_date %>
        <%= button_to "Edit", edit_reservation_path, method: :get %>
        <%= button_to "Delete", reservation_path, method: :delete %>            
        <%= button_to "Leave Review", new_review_path, method: :get %>  
    </div>
</div>