config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :houses
  resources :reservations
  resources :hosts
  resources :guests

  get '/login', to: "auth#login", as: "login"
  post '/login', to: "auth#verify_first_name"

  get '/logout', to: "auth#logout", as: "logout"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1">Airvnv</span>
      <a class="btn btn-primary " href="<%= login_path %>" role="button">Login</a>
      <a class="btn btn-primary" href="<%= logout_path %>" role="button">Logout</a>
      
      <a class="btn btn-primary" href="<%= new_guest_path %>" role="button">Sign Up As Guest</a>
      <a class="btn btn-primary" href="<%= new_host_path %>" role="button">Sign Up As Host</a>
    </nav>
    <%= yield %>
  </body>
</html>

<style>

body {
 background-image: url("https://i.giphy.com/media/UqqVRaP8y4uo1GNxbN/giphy.webp");
 background-color: #696969;
 background-repeat: no-repeat;
  background-size: cover;
}



</style>